version: "3.9"

services:
  webapp:
    build:
      context: ./app
    ports:
      - "80:8080"
    restart: always
    networks: 
      - spm-onestop-net
    extra_hosts: 
      -  "host.docker.internal:host-gateway"
      
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    restart: always
    networks: 
      - spm-onestop-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
+     - DB_HOST=db
+     - DB_PORT=27017
+     - DB_NAME=spm-onestop
+     - DB_TEST_NAME=spm-onestop-test
      
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - spm-onestop-net
    
      
networks:
  spm-onestop-net:
    driver: bridge