### Create Quiz

POST http://localhost:3000/api/quiz/new
Content-Type: application/json


{
    "courseCode": "HP101",
    "section": 1,
    "quizName": "Printer Functions",
    "timeAllowed": 3600,
    "questions": [
        {
            "questionText": "Which of the following do not have SCAN function",
            "questionType": "MCQ",
            "questionMarks": 2,
            "answerOptions": [
                "HP LaserJet Pro M15w Printer",
                "HP LaserJet Pro MFP M28w Printer",
                "HP Color LaserJet Pro MFP M283fdw",
                "HP LaserJet Pro MFP M227fdw"
            ],
            "correctAnswers": [
                "HP LaserJet Pro M15w Printer"
            ]
        },
        {
            "questionText": "Which of the following do not have SCAN function",
            "questionType": "MCQ",
            "questionMarks": 4,
            "answerOptions": [
                "HP LaserJet Pro M15w Printer",
                "HP LaserJet Pro MFP M28w Printer",
                "HP Color LaserJet Pro MFP M283fdw",
                "HP LaserJet Pro MFP M227fdw"
            ],
            "correctAnswers": [
                "HP LaserJet Pro M15w Printer"
            ]
        },
        {
            "questionText": "Which of the following do not have SCAN function",
            "questionType": "MCQ",
            "answerOptions": [
                "HP LaserJet Pro M15w Printer",
                "HP LaserJet Pro MFP M28w Printer",
                "HP Color LaserJet Pro MFP M283fdw",
                "HP LaserJet Pro MFP M227fdw"
            ],
            "correctAnswers": [
                "HP LaserJet Pro M15w Printer"
            ]
        }
    ]
}