# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  test-cases:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.0', '4.2', '4.4']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    # Set Environ Variables
    env:
      DB_HOST: localhost
      DB_PORT: 27017
      DB_NAME: spm-onestop
      DB_TEST_NAME: spm-onestop-test

    steps:
    
    - name: Git Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - run: npm ci
    - run: npm test